apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-secret
      containers:
      - name: frontend
        image: kjwong/udagram-frontend:1.0.1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: udagram-env
        env: 
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: pg-user-pass
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-user-pass
                key: password
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: "/.aws/credentials"
        volumeMounts:
          - name: aws-credentials
            readOnly:
            mountPath: "/.aws"
        ports:
        - containerPort: 80
