language: node_js
node_js:
  - 13

services:
  - docker

env:
  - REVERSE_PROXY_VERSION=1.0.0
  - API_USER_VERSION=1.0.0
  - API_FEED_VERSION=1.0.0
  - FRONTEND_VERSION=1.0.0

script:
  - docker-compose --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy kjwong/reverseproxy:latest
  - docker tag udagram-api-user kjwong/udagram-api-user:latest
  - docker tag udagram-api-feed kjwong/udagram-api-feed:latest
  - docker tag udagram-frontend kjwong/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kjwong/reverseproxy:latest
  - docker push kjwong/udagram-api-user:latest
  - docker push kjwong/udagram-api-feed:latest
  - docker push kjwong/udagram-frontend:latest